export const currency = [
  { unit: "USD", country: "미국 달러" },
  { unit: "KRW", country: "한국 원" },
  { unit: "EUR", country: "유로" },
  { unit: "JPY", country: "일본 엔" },
  { unit: "GBP", country: "영국 파운드" },
  { unit: "CNY", country: "중국 위안" },
  { unit: "HKD", country: "홍콩 달러" },
  { unit: "SGD", country: "싱가포르 달러" },
  { unit: "CHF", country: "스위스 프랑" },
  { unit: "AUD", country: "호주 달러" },
  { unit: "CAD", country: "캐나다 달러" },
  { unit: "NZD", country: "뉴질랜드 달러" },
  { unit: "INR", country: "인도 루피" },
  { unit: "MXN", country: "멕시코 페소" },
  { unit: "BRL", country: "브라질 레알" },
  { unit: "ZAR", country: "남아프리카 랜드" },
  { unit: "TRY", country: "터키 리라" },
  { unit: "RUB", country: "러시아 루블" },
  { unit: "SEK", country: "스웨덴 크로나" },
  { unit: "NOK", country: "노르웨이 크로네" },
  { unit: "DKK", country: "덴마크 크로네" },
  { unit: "PLN", country: "폴란드 즈로티" },
  { unit: "ILS", country: "이스라엘 셰켈" },
  { unit: "HUF", country: "헝가리 포린트" },
  { unit: "CZK", country: "체코 코루나" },
  { unit: "THB", country: "태국 바트" },
  { unit: "MYR", country: "말레이시아 링깃" },
  { unit: "PHP", country: "필리핀 페소" },
  { unit: "IDR", country: "인도네시아 루피아" },
];
